apiVersion: v1
kind: Service
metadata:
  name: quantum-avenger-dashboard
  labels: {app: quantum-avenger, component: dashboard}
spec:
  type: LoadBalancer
  selector: {app: quantum-avenger, component: dashboard}
  ports:
    - port: 80
      targetPort: 8501
