global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert_rules.yml

scrape_configs:
  - job_name: quantum-avenger-app
    static_configs:
      - targets: ["app:9090"]
  - job_name: quantum-avenger-dashboard
    static_configs:
      - targets: ["dashboard:8501"]
